services:
  db:
    image: postgres:16
    container_name: main_db
    environment:
      POSTGRES_DB: tralalelo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    volumes:
      - ./backend/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - "5432:5432"
    networks:
      - api_network

networks:
  api_network:
    driver: bridge