FROM python:3.12

WORKDIR /app

COPY backend/app/requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

COPY . /app

CMD ["python", "-m", "backend.app.main"]