# Здесь собраны все схемы запросов, ответов для хэндлеров
from .board import (
    AbsoluteFullBoardInfo,
    AllowBoard,
    BoardOut,
    ColumnOut,
    CommentCreate,
    CommentData,
    CommentOut,
    CreateBoard,
    CreateColumn,
    FullBoardInfo,
    SubtaskCreate,
    SubtaskUpdate,
    TaskCreate,
    TaskOut,
    TaskShortOut,
    TaskUpdate,
    UpdateBoard,
    UpdateColumn,
    UpdateColumnsPos,
    UpdateTaskPos,
)
from .notifications import CreateNotification, NotificationInfo, UpdateNotification
from .service_response import Error, ServiceMessage, SuccessResponse
from .user import (
    BaseUserInfo,
    BoardUserPreview,
    FullInfo,
    Login,
    RegUser,
    UpdatePass,
    UserPreview,
)

__all__ = [
    "BaseUserInfo",
    "RegUser",
    "FullInfo",
    "Login",
    "FullBoardInfo",
    "AbsoluteFullBoardInfo",
    "CreateColumn",
    "TaskCreate",
    "SubtaskCreate",
    "CommentCreate",
    "CreateBoard",
    "UpdateColumnsPos",
    "TaskUpdate",
    "ColumnOut",
    "TaskShortOut",
    "BoardOut",
    "TaskOut",
    "SubtaskUpdate",
    "UserPreview",
    "UpdatePass",
    "Error",
    "BoardUserPreview",
    "ServiceMessage",
    "UpdateColumn",
    "UpdateTaskPos",
    "CreateNotification",
    "NotificationInfo",
    "UpdateNotification",
    "AllowBoard",
    "CommentOut",
    "UpdateBoard",
    "SuccessResponse",
    "CommentData",
]
